### ISSUE TITLE
关于去除url中的#和Angular开发必备技巧（持续更新）有点疑问求教

### ISSUE THREAD

**Issue by poetrylife** [deepthan/blog-angular#11]
1. 按照您的方法配置了去除路由中的#，页面在登录页面刷新会403，您知道什么原因吗？
2. Angular开发必备技巧（持续更新）这个我fork到我的仓库了可以和您一起共同维护吗？最近公司也开始用Angular了。

**Comment by deepthan** [comment]
出现403是不是后端加了权限控制？可以fork啊，一起学习交流。
